import type { CardType, CelebrationCardData } from "./types";

export const TYPE_LABELS: Record<CardType, string> = {
  birth: "출산",
  wedding: "결혼",
  graduation: "졸업",
  award: "수상",
  admission: "합격",
  birthday: "생일",
  free: "자유",
};

export const PRESETS: Record<CardType, CelebrationCardData> = {
  birth: {
    type: "birth",
    headline: "새 생명의 탄생을\n온 마음으로 축하합니다",
    recipientPrefix: "연세교육공학의 소중한",
    recipientName: "홍길동",
    recipientHonorific: "선생님",
    paragraphs: [
      "이 세상에 아름다운 생명이 찾아왔다는 소식에 연세교육공학 가족 모두가 함께 기뻐하고 있습니다. 새 생명의 탄생은 그 자체로 **경이롭고 찬란한 선물**입니다.",
      "앞으로 펼쳐질 긴 여정에서 아이가 **건강하고 행복하게** 성장하기를, 그리고 선생님께서도 **더없이 깊은 기쁨**을 누리시길 바랍니다.",
      "바쁜 연구 생활 속에서도 이렇게 귀한 인연을 맺으신 선생님과 가족 모두에게 따뜻한 응원을 보냅니다. 언제나 연세교육공학이 함께하겠습니다.",
    ],
    closing: "진심으로 축하드립니다.",
    senderSuffix: "연세교육공학 드림",
    photoUrl: "",
    usePhotoPlaceholder: true,
  },
  wedding: {
    type: "wedding",
    headline: "두 분의 아름다운\n결혼을 축하합니다",
    recipientPrefix: "연세교육공학의 소중한",
    recipientName: "홍길동",
    recipientHonorific: "선생님",
    paragraphs: [
      "사랑하는 두 분이 한 마음으로 새로운 출발을 하신다는 소식에 진심으로 기쁜 마음을 전합니다. 오늘의 이 날은 **평생 빛나는 기억**으로 남을 것입니다.",
      "앞으로 펼쳐질 두 분의 여정이 언제나 **서로에 대한 존중과 사랑**으로 가득하기를, 그리고 함께 이루어 나갈 **꿈이 아름답게 피어나기를** 기원합니다.",
      "연세교육공학 가족 모두가 두 분의 새로운 시작을 진심으로 응원합니다.",
    ],
    closing: "결혼을 진심으로 축하드립니다.",
    senderSuffix: "연세교육공학 드림",
    photoUrl: "",
    usePhotoPlaceholder: true,
  },
  graduation: {
    type: "graduation",
    headline: "학위 취득을\n진심으로 축하드립니다",
    recipientPrefix: "연세교육공학의 자랑스러운",
    recipientName: "홍길동",
    recipientHonorific: "선생님",
    paragraphs: [
      "오랜 시간 학업과 연구에 매진하여 마침내 학위를 취득하신 선생님께 **진심 어린 축하**를 드립니다. 이 성취는 선생님의 **끊임없는 노력과 열정**의 결실입니다.",
      "연구자로서 걸어오신 여정을 함께 지켜보며 저희 모두 큰 **자랑스러움과 감동**을 느꼈습니다. 이제 더 넓은 세계에서 선생님의 역량이 빛을 발하리라 믿습니다.",
      "앞으로도 연세교육공학과 함께 교육공학의 발전에 기여해 주시기를 기대합니다. 언제나 응원하겠습니다.",
    ],
    closing: "졸업을 진심으로 축하드립니다.",
    senderSuffix: "연세교육공학 드림",
    photoUrl: "/yonsei-campus.jpg",
    usePhotoPlaceholder: false,
  },
  award: {
    type: "award",
    headline: "수상을\n진심으로 축하드립니다",
    recipientPrefix: "연세교육공학의 자랑",
    recipientName: "홍길동",
    recipientHonorific: "선생님",
    paragraphs: [
      "선생님의 탁월한 연구와 헌신적인 노력이 이번 수상으로 빛을 발하게 된 것을 연세교육공학 가족 모두와 함께 **진심으로 기쁘게** 생각합니다.",
      "이번 수상은 선생님의 **깊은 전문성과 열정**이 이룬 결실임과 동시에, 우리 모두에게 **귀감이 되는 소중한 사례**입니다.",
      "앞으로도 더욱 빛나는 연구 성과로 교육공학 발전에 기여해 주시기를 기대합니다.",
    ],
    closing: "수상을 다시 한번 축하드립니다.",
    senderSuffix: "연세교육공학 드림",
    photoUrl: "",
    usePhotoPlaceholder: true,
  },
  admission: {
    type: "admission",
    headline: "합격을\n진심으로 축하드립니다",
    recipientPrefix: "연세교육공학의 새로운",
    recipientName: "홍길동",
    recipientHonorific: "선생님",
    paragraphs: [
      "합격이라는 기쁜 소식에 연세교육공학 가족 모두가 **함께 기뻐하며** 선생님을 진심으로 환영합니다. 이 시작은 선생님의 **새로운 여정의 출발점**입니다.",
      "앞으로의 배움과 성장의 길 위에서 연세교육공학이 언제나 **든든한 동반자**가 되겠습니다. 함께라면 더 멀리, 더 깊이 나아갈 수 있습니다.",
      "이제 함께 교육공학의 지식과 열정을 나누며 **의미 있는 연구 공동체**를 만들어 가겠습니다. 환영합니다.",
    ],
    closing: "합격을 다시 한번 축하드립니다.",
    senderSuffix: "연세교육공학 드림",
    photoUrl: "",
    usePhotoPlaceholder: true,
  },
  birthday: {
    type: "birthday",
    headline: "생일을\n진심으로 축하드립니다",
    recipientPrefix: "연세교육공학의 소중한",
    recipientName: "홍길동",
    recipientHonorific: "선생님",
    paragraphs: [
      "선생님의 뜻깊은 생일을 맞이하여 연세교육공학 가족 모두가 **따뜻한 마음**을 전합니다. 오늘 하루가 선생님께 **특별하고 행복한 하루**가 되기를 바랍니다.",
      "바쁜 연구 일정 속에서도 언제나 열정을 잃지 않으시는 선생님의 모습이 우리 모두에게 **큰 힘과 영감**이 됩니다.",
      "앞으로도 건강하고 행복하게, 그리고 **더 큰 꿈을 향해** 나아가시기를 진심으로 응원합니다.",
    ],
    closing: "생일을 진심으로 축하드립니다.",
    senderSuffix: "연세교육공학 드림",
    photoUrl: "",
    usePhotoPlaceholder: true,
  },
  free: {
    type: "free",
    headline: "진심을 담아\n전합니다",
    recipientPrefix: "연세교육공학의 소중한",
    recipientName: "홍길동",
    recipientHonorific: "선생님",
    paragraphs: [
      "오늘 이 순간, 연세교육공학 가족 모두의 따뜻한 마음과 함께합니다.",
      "언제나 선생님의 모든 순간을 응원합니다.",
    ],
    closing: "진심으로 감사하고 축하드립니다.",
    senderSuffix: "연세교육공학 드림",
    photoUrl: "",
    usePhotoPlaceholder: true,
  },
};
