import type { Seminar, SeminarSession } from "@/types";

export const MOCK_SEMINARS: Seminar[] = [
  {
    id: "s1",
    title: "생성형 AI와 교수설계의 재정의",
    description:
      "ChatGPT, Claude 등 생성형 AI가 교수설계 프로세스를 어떻게 변화시키고 있는지 살펴봅니다. ADDIE 모델의 각 단계에서 AI를 활용하는 구체적 사례를 다룹니다.",
    date: "2026-03-19",
    time: "19:00",
    location: "교육과학관 203호",
    speaker: "김민수",
    speakerBio: "연세대 교육학과 박사과정, AI 교육 연구",
    posterUrl: "https://placehold.co/400x566?text=AI+%EA%B5%90%EC%88%98%EC%84%A4%EA%B3%84",
    maxAttendees: 30,
    attendeeIds: ["2", "3", "4", "100"],
    sessions: [
      { id: "ss1", seminarId: "s1", title: "생성형 AI 개론과 교육 적용", speaker: "김민수", time: "19:00", duration: 30, order: 1 },
      { id: "ss2", seminarId: "s1", title: "ADDIE 모델에서의 AI 활용 사례", speaker: "박지현", speakerBio: "교육공학 석사과정", time: "19:30", duration: 25, order: 2 },
      { id: "ss3", seminarId: "s1", title: "토론 및 Q&A", speaker: "전체", time: "19:55", duration: 20, order: 3 },
    ],
    status: "upcoming",
    createdBy: "3",
    createdAt: "2026-03-10T10:00:00Z",
    updatedAt: "2026-03-10T10:00:00Z",
  },
  {
    id: "s2",
    title: "VR/AR 기반 몰입형 학습 환경 설계",
    description:
      "가상현실과 증강현실 기술을 활용한 교육 콘텐츠 설계 방법론을 소개합니다. Meta Quest, Apple Vision Pro 등 최신 디바이스 활용 사례를 포함합니다.",
    date: "2026-03-26",
    time: "19:00",
    location: "교육과학관 203호",
    speaker: "이서연",
    speakerBio: "연세대 교육학과 석사과정, VR 교육 연구",
    maxAttendees: 25,
    attendeeIds: ["2", "100"],
    status: "upcoming",
    createdBy: "3",
    createdAt: "2026-03-10T10:00:00Z",
    updatedAt: "2026-03-10T10:00:00Z",
  },
  {
    id: "s3",
    title: "학습 분석(Learning Analytics) 실습 워크숍",
    description:
      "R과 Python을 활용한 학습 데이터 분석 실습을 진행합니다. LMS 로그 데이터를 기반으로 학습자 행동 패턴을 분석하는 방법을 배웁니다.",
    date: "2026-04-02",
    time: "14:00",
    location: "교육과학관 B1 컴퓨터실",
    speaker: "정다은",
    speakerBio: "연세대 교육학과 박사과정, 학습분석 전공",
    maxAttendees: 20,
    attendeeIds: [],
    status: "upcoming",
    createdBy: "3",
    createdAt: "2026-03-12T09:00:00Z",
    updatedAt: "2026-03-12T09:00:00Z",
  },
  {
    id: "s4",
    title: "마이크로크레덴셜의 현재와 미래",
    description:
      "디지털 배지, 마이크로디그리 등 마이크로크레덴셜 트렌드와 국내외 사례를 분석합니다. 고등교육에서의 적용 가능성을 토론합니다.",
    date: "2026-03-05",
    time: "19:00",
    location: "교육과학관 203호",
    speaker: "최현우",
    speakerBio: "연세대 교육학과 석사과정, 교육정책 연구",
    posterUrl: "https://placehold.co/400x566?text=%EB%A7%88%EC%9D%B4%ED%81%AC%EB%A1%9C%ED%81%AC%EB%A0%88%EB%8D%B4%EC%85%9C",
    attendeeIds: ["2", "3", "4", "5", "100"],
    sessions: [
      { id: "ss4", seminarId: "s4", title: "마이크로크레덴셜 개념과 글로벌 동향", speaker: "최현우", time: "19:00", duration: 25, order: 1 },
      { id: "ss5", seminarId: "s4", title: "국내 대학 적용 사례 분석", speaker: "한소영", speakerBio: "교육정책 석사과정", time: "19:25", duration: 25, order: 2 },
    ],
    status: "completed",
    createdBy: "3",
    createdAt: "2026-02-25T10:00:00Z",
    updatedAt: "2026-03-06T10:00:00Z",
  },
  {
    id: "s5",
    title: "교육용 챗봇 설계 및 프롬프트 엔지니어링",
    description:
      "교육 현장에서 활용할 수 있는 AI 챗봇을 설계하고, 효과적인 프롬프트 작성법을 실습합니다.",
    date: "2026-02-26",
    time: "19:00",
    location: "교육과학관 203호",
    speaker: "김민수",
    speakerType: "member",
    attendeeIds: ["3", "4", "5", "6"],
    status: "completed",
    createdBy: "3",
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-02-27T10:00:00Z",
  },
  {
    id: "s6",
    title: "AI 시대의 교수설계 재정의",
    description:
      "인공지능 기술의 발전이 교수설계의 패러다임을 어떻게 변화시키고 있는지 살펴봅니다. ADDIE, SAM 등 전통적 교수설계 모형의 AI 시대 재해석과 새로운 설계 프레임워크를 제안합니다.",
    date: "2026-04-05",
    time: "14:00",
    location: "연세대 백양관 대강당",
    speaker: "김영진",
    speakerBio: "AI 기반 교육 시스템 전문가. 前 교육부 에듀테크 정책자문위원. 저서 '교육공학의 미래' 등.",
    speakerType: "guest",
    speakerAffiliation: "한국교육공학대학교",
    speakerPosition: "교수",
    speakerPhotoUrl: "https://placehold.co/120x120?text=Guest",
    maxAttendees: 50,
    attendeeIds: ["2", "3", "4"],
    status: "upcoming",
    createdBy: "2",
    createdAt: "2026-03-12T08:00:00Z",
    updatedAt: "2026-03-12T08:00:00Z",
  },
  {
    id: "s7",
    title: "실감형 교육 콘텐츠의 현재와 미래",
    description:
      "VR/AR/MR 기술을 활용한 교육 콘텐츠 개발 동향과 효과성 연구 결과를 공유합니다.",
    date: "2026-03-12",
    time: "19:00",
    location: "교육과학관 203호",
    speaker: "박서준",
    speakerBio: "XR 교육 콘텐츠 설계 전문가. Meta Education 파트너. VR 기반 의학교육 프로젝트 다수 수행.",
    speakerType: "guest",
    speakerAffiliation: "OO에듀테크",
    speakerPosition: "HRD팀장",
    speakerPhotoUrl: "https://placehold.co/120x120?text=Guest2",
    attendeeIds: ["2", "3", "5", "100"],
    status: "completed",
    createdBy: "3",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-13T10:00:00Z",
  },
];
